version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-animation-fe
    container_name: rag-animation-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - raganimation-fe

  web:
    image: nginx:alpine
    container_name: rag-animation-nginx
    restart: unless-stopped
    ports:
      - "8007:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - raganimation-fe

networks:
  raganimation-fe:
    driver: bridge
